name: senselet_driver
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  fcm_config: ^3.5.1
  graphql_flutter: ^5.1.2
  sizer: ^2.0.15
  firebase_analytics: ^10.1.6
  shared_preferences: ^2.0.20
  get_it: ^7.2.0
  cached_network_image: ^3.2.3
  intl: ^0.18.0
  shimmer: ^2.0.0
  country_picker: ^2.0.20
  pinput: ^2.2.31
  font_awesome_flutter: ^10.4.0
  lottie: ^2.3.0
  awesome_snackbar_content: ^0.1.1
  geocoding: ^2.1.0
  google_maps_flutter: ^2.2.5
  map_picker: ^0.0.3
  dotted_line: ^3.1.0
  qr_flutter: ^4.0.0
  jwt_decoder: ^2.0.1
  permission_handler: ^10.2.0
  geolocator: ^9.0.2
  url_launcher: ^6.1.11
  badges: ^3.1.1
  timeago: ^3.4.0


dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter:
  assets:

    - assets/images/
    - assets/lottie/
    - assets/icons/

  uses-material-design: true
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
